### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by JedWatson** [JedWatson/happiness#6]
Currently seeing:

```
  api usage

    ✓ no error while linting
    ✓ result is an object
    ✓ error count 61

    ✗ error filepath correct
    -------------------------
      operator: equal
      expected: '/Users/Jed/Development/packages/happiness/bin/cmd.js'
      actual:   'bin/cmd.js'
      at: zalgoSafe (/Users/Jed/Development/packages/happiness/node_modules/standard-engine/node_modules/dezalgo/dezalgo.js:20:10)

    ✓ first missing semicolon message
    ✓ second missing semicolon message



  Failed Tests: There was 1 failure

    api usage

      ✗ error filepath correct


  total:     6
  passing:   5
  failing:   1
  duration:  355ms
```

This may not be worth looking into until we fix #5 

@dcousens, any feedback?

**Comment by dcousens** [comment]
I'd say blocked on #5, and probably going to be resolved by it too.

**Comment by wesleytodd** [comment]
FWIW, this would not be fixed directly by merging because their error count is 0.  

This test is very brittle because it means any change in the upstream that changes the number of errors would fail for this repo's tests.  A better change would be to make this repo's version of `bin/cmd.js` compatible with the rules herein.  Then when pulling in their changes all that needs to be done is fix the actual reported errors.

**Comment by wesleytodd** [comment]
Fixed in new version
